esphome:
  name: officelamp
  friendly_name: OfficeLamp

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:
  password: "REDACTED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Officelamp Fallback Hotspot"
    password: "REDACTED"

captive_portal:

light:
  - platform: monochromatic
    output: gpio_15
    name: "Office Lamp"
    id: office_lamp

switch:
  - platform: gpio
    name: "Magnifier Light"
    pin: GPIO18
    id: magnifier_lamp

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pulldown: true
    id: lamp_button1
    name: "Lamp Button"
    on_press:
      then:
        - if:
            condition:
              light.is_on: office_lamp
            then:
              - light.turn_off: office_lamp
        - if:
            condition:
              light.is_off: office_lamp
            then:
              - light.turn_on:
                  id: office_lamp
                  brightness: 100%

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pulldown: true
    id: magnifier_button
    name: "Magnifier Button"
    on_press:
      - then:
          - switch.toggle: magnifier_lamp

output:
  - platform: ledc
    pin: GPIO15
    id: gpio_15
    min_power: 0.25
    zero_means_zero: true
